// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace S_InterModels.Models.Optimus
{
    [Table("Users", Schema = "usr")]
    public partial class Users
    {
        [Key]
        [Column("usrUserId")]
        [StringLength(10)]
        [Unicode(false)]
        public string UsrUserId { get; set; }
        [Required]
        [Column("usrName")]
        [StringLength(100)]
        [Unicode(false)]
        public string UsrName { get; set; }
        [Required]
        [Column("usrMail")]
        [StringLength(255)]
        [Unicode(false)]
        public string UsrMail { get; set; }
        [Required]
        [Column("usrProfil")]
        [StringLength(50)]
        [Unicode(false)]
        public string UsrProfil { get; set; }
        [Column("usrIsValid")]
        public bool UsrIsValid { get; set; }
        [Column("usrIsLeader")]
        public bool UsrIsLeader { get; set; }
        [Column("usrIsDeveloper")]
        public bool UsrIsDeveloper { get; set; }
        [Column("usrIsPartner")]
        public bool UsrIsPartner { get; set; }
        [Column("usrIsDirection")]
        public bool UsrIsDirection { get; set; }
        [Column("usrIsScs")]
        public bool UsrIsScs { get; set; }
        [Column("usrIsRr")]
        public bool UsrIsRr { get; set; }
        [Column("usrIsRrd")]
        public bool UsrIsRrd { get; set; }
        [Column("usrIsNew")]
        public bool UsrIsNew { get; set; }
        [Column("usrIsTech")]
        public bool UsrIsTech { get; set; }
        [Column("usrIsWorkshop")]
        public bool UsrIsWorkshop { get; set; }
        [Column("usrIsSupervisor")]
        public bool UsrIsSupervisor { get; set; }
        [Column("usrIsEngineer")]
        public bool UsrIsEngineer { get; set; }
        [Column("usrIsGestAdmin")]
        public bool UsrIsGestAdmin { get; set; }
        [Column("usrIsRh")]
        public bool UsrIsRh { get; set; }
        [Column("usrIsAppli")]
        public bool? UsrIsAppli { get; set; }
        [Column("ptnPartnerId")]
        [StringLength(45)]
        [Unicode(false)]
        public string PtnPartnerId { get; set; }
        [Column("usrIsQhse")]
        public bool UsrIsQhse { get; set; }
        [Column("usrIsVariablePolicyMaker")]
        public bool UsrIsVariablePolicyMaker { get; set; }
        [Column("usrIsWorkshopManager")]
        public bool UsrIsWorkshopManager { get; set; }
        [Column("usrIsBackOffice")]
        public bool UsrIsBackOffice { get; set; }
        [Column("usrIsSalesforceKeyUser")]
        public bool UsrIsSalesforceKeyUser { get; set; }
        [Column("usrIsExpUser")]
        public bool UsrIsExpUser { get; set; }
        [Column("usrIsExpManage")]
        public bool UsrIsExpManage { get; set; }
        [Column("usrIsExpValidator")]
        public bool UsrIsExpValidator { get; set; }
        [Column("usrIsExpLeader")]
        public bool UsrIsExpLeader { get; set; }
        [Column("usrSalesforceToken")]
        [StringLength(50)]
        [Unicode(false)]
        public string UsrSalesforceToken { get; set; }
        [Column("usrSalesforceTokenSandbox")]
        [StringLength(50)]
        [Unicode(false)]
        public string UsrSalesforceTokenSandbox { get; set; }
        [Column("usrIsValidInSalesForce")]
        public bool UsrIsValidInSalesForce { get; set; }
        [Column("usrIdSalesForceUser")]
        [StringLength(25)]
        [Unicode(false)]
        public string UsrIdSalesForceUser { get; set; }
        [Column("usrIdSalesForceServiceResource")]
        [StringLength(25)]
        [Unicode(false)]
        public string UsrIdSalesForceServiceResource { get; set; }
        [Column("usrGuid")]
        [StringLength(36)]
        [Unicode(false)]
        public string UsrGuid { get; set; }
        [Column("usrIsTechPlus")]
        public bool UsrIsTechPlus { get; set; }
        [Column("usrIsEngineerManager")]
        public bool UsrIsEngineerManager { get; set; }
        [Column("usrIsMetrologyAdmin")]
        public bool UsrIsMetrologyAdmin { get; set; }
    }
}